ALTER TABLE alerts.alerts ADD COLUMN IF NOT EXISTS acknowledged BOOLEAN DEFAULT FALSE;
ALTER TABLE alerts.alerts ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE alerts.alerts ADD COLUMN IF NOT EXISTS severity VARCHAR(50);
ALTER TABLE alerts.alerts ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE alerts.alerts ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE;