// lib/utils/pdfExport.ts
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Transaction {
  id: string;
  date: string;
  description: string;
  category: string;
  amount: number;
  type: 'INCOME' | 'EXPENSE';
}

interface ExportOptions {
  title?: string;
  dateRange?: string;
  includeChart?: boolean;
  orientation?: 'portrait' | 'landscape';
}

export const exportTransactionsToPDF = (
  transactions: Transaction[],
  options: ExportOptions = {}
) => {
  const {
    title = 'Transaction Report',
    dateRange = 'All Time',
    orientation = 'portrait'
  } = options;

  // Create new PDF document
  const doc = new jsPDF({
    orientation,
    unit: 'mm',
    format: 'a4'
  });

  // Add header
  doc.setFontSize(20);
  doc.setTextColor(147, 51, 234); // Purple
  doc.text(title, 14, 20);

  // Add date range
  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128); // Gray
  doc.text(`Period: ${dateRange}`, 14, 28);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 33);

  // Add summary statistics
  const totalIncome = transactions
    .filter(t => t.type === 'INCOME')
    .reduce((sum, t) => sum + t.amount, 0);
  
  const totalExpenses = transactions
    .filter(t => t.type === 'EXPENSE')
    .reduce((sum, t) => sum + t.amount, 0);
  
  const netAmount = totalIncome - totalExpenses;

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Summary', 14, 43);
  
  doc.setFontSize(10);
  doc.setTextColor(34, 197, 94); // Green
  doc.text(`Total Income: $${totalIncome.toFixed(2)}`, 14, 50);
  
  doc.setTextColor(239, 68, 68); // Red
  doc.text(`Total Expenses: $${totalExpenses.toFixed(2)}`, 14, 56);
  
  doc.setTextColor(0, 0, 0);
  doc.text(`Net Amount: $${netAmount.toFixed(2)}`, 14, 62);

  // Add line separator
  doc.setDrawColor(229, 231, 235);
  doc.line(14, 67, 196, 67);

  // Add transactions table
  const tableData = transactions.map(t => [
    new Date(t.date).toLocaleDateString(),
    t.description,
    t.category,
    t.type,
    `$${t.amount.toFixed(2)}`
  ]);

  autoTable(doc, {
    startY: 72,
    head: [['Date', 'Description', 'Category', 'Type', 'Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [147, 51, 234], // Purple
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: 'bold'
    },
    bodyStyles: {
      fontSize: 9
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251]
    },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 60 },
      2: { cellWidth: 35 },
      3: { cellWidth: 25 },
      4: { cellWidth: 30, halign: 'right' }
    },
    didParseCell: (data) => {
      // Color code amounts
      if (data.column.index === 4 && data.section === 'body') {
        const row = transactions[data.row.index];
        if (row.type === 'INCOME') {
          data.cell.styles.textColor = [34, 197, 94]; // Green
        } else {
          data.cell.styles.textColor = [239, 68, 68]; // Red
        }
      }
    }
  });

  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by FinTrack',
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  // Save the PDF
  const fileName = `fintrack-transactions-${new Date().getTime()}.pdf`;
  doc.save(fileName);
};

export const exportBudgetReportToPDF = (
  budgets: any[],
  options: ExportOptions = {}
) => {
  const {
    title = 'Budget Report',
    dateRange = 'Current Period',
    orientation = 'portrait'
  } = options;

  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });

  // Header
  doc.setFontSize(20);
  doc.setTextColor(147, 51, 234);
  doc.text(title, 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text(`Period: ${dateRange}`, 14, 28);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 33);

  // Summary
  const totalBudget = budgets.reduce((sum, b) => sum + b.amount, 0);
  const totalSpent = budgets.reduce((sum, b) => sum + (b.spent || 0), 0);
  const remaining = totalBudget - totalSpent;

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Summary', 14, 43);
  
  doc.setFontSize(10);
  doc.text(`Total Budget: $${totalBudget.toFixed(2)}`, 14, 50);
  doc.setTextColor(239, 68, 68);
  doc.text(`Total Spent: $${totalSpent.toFixed(2)}`, 14, 56);
  doc.setTextColor(34, 197, 94);
  doc.text(`Remaining: $${remaining.toFixed(2)}`, 14, 62);

  doc.setDrawColor(229, 231, 235);
  doc.line(14, 67, 196, 67);

  // Budgets table
  const tableData = budgets.map(b => {
    const spent = b.spent || 0;
    const percentage = (spent / b.amount) * 100;
    return [
      b.category,
      `$${b.amount.toFixed(2)}`,
      `$${spent.toFixed(2)}`,
      `${percentage.toFixed(1)}%`,
      `$${(b.amount - spent).toFixed(2)}`
    ];
  });

  autoTable(doc, {
    startY: 72,
    head: [['Category', 'Budget', 'Spent', 'Usage %', 'Remaining']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [147, 51, 234],
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: 'bold'
    },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'center' },
      4: { halign: 'right' }
    },
    didParseCell: (data) => {
      if (data.column.index === 3 && data.section === 'body') {
        const percentage = parseFloat(data.cell.text[0]);
        if (percentage >= 100) {
          data.cell.styles.textColor = [239, 68, 68]; // Red
          data.cell.styles.fontStyle = 'bold';
        } else if (percentage >= 80) {
          data.cell.styles.textColor = [249, 115, 22]; // Orange
        }
      }
    }
  });

  const fileName = `fintrack-budget-report-${new Date().getTime()}.pdf`;
  doc.save(fileName);
};