services:
  postgres:
    image: postgres:16
    container_name: fintrack-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintrack
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [fintrack-network]

  redis:
    image: redis:7
    container_name: fintrack-redis
    ports: ["6379:6379"]
    networks: [fintrack-network]

  # Single-broker Kafka in KRaft mode (no ZooKeeper)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: fintrack-kafka
    ports:
      - "9092:9092"        # host -> PLAINTEXT_HOST
      - "9101:9101"        # optional JMX
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk   # any 22-char base64-like ID is fine for local
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks: [fintrack-network]

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.2
    container_name: fintrack-kafdrop
    depends_on: [kafka]
    ports: ["19000:9000"]
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"   # use the internal listener
    networks: [fintrack-network]

networks:
  fintrack-network:
    driver: bridge

volumes:
  pgdata:
  kafka_data:
